-- Vakanso / JobScan initial Supabase schema.
-- Run this once on a fresh Supabase project.

-- Core scraper tables ---------------------------------------------------------

create table public.glorri_companies (
  id bigint generated by default as identity not null,
  slug text null,
  name text null,
  logo text null,
  created_at timestamp with time zone not null default now(),
  constraint glorri_companies_pkey primary key (id)
) TABLESPACE pg_default;

create table public.glorri_vacancies (
  id bigint generated by default as identity not null,
  title text null,
  slug text null,
  "postedDate" text null,
  "jobFunction" text null,
  "careerLevel" text null,
  location text null,
  type text null,
  detail_url text null,
  text text null,
  vacancy_about jsonb null,
  benefits jsonb null,
  apply_url text null,
  company_id bigint null,
  created_at timestamp with time zone not null default now(),
  tech_stack jsonb null,
  constraint glorri_vacancies_pkey primary key (id),
  constraint glorri_vacancies_company_id_fkey foreign KEY (company_id) references glorri_companies (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.js_companies (
  id bigint generated by default as identity not null,
  title text not null,
  logo text null,
  logo_mini text null,
  first_char text not null,
  created_at timestamp with time zone not null default now(),
  text text null,
  address text null,
  phones jsonb null,
  sites jsonb null,
  email jsonb null,
  cover text null,
  coordinates jsonb not null,
  constraint companies_pkey primary key (id)
) TABLESPACE pg_default;

create table public.js_vacancies (
  id bigint not null,
  title text not null,
  created_at timestamp with time zone not null,
  slug text not null,
  company_id bigint not null,
  salary bigint null,
  deadline_at timestamp with time zone null,
  text text null,
  tech_stack jsonb null,
  constraint vacancies_pkey primary key (id),
  constraint vacancies_id_key unique (id),
  constraint vacancies_company_id_fkey foreign KEY (company_id) references js_companies (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.duplicate_jobs (
  glorri_id bigint not null,
  jobsearch_id bigint not null,
  score numeric(6, 4) not null,
  matched_at timestamp with time zone not null default now(),
  constraint duplicate_jobs_pkey primary key (glorri_id),
  constraint duplicate_jobs_jobsearch_id_key unique (jobsearch_id),
  constraint duplicate_jobs_glorri_id_fkey foreign KEY (glorri_id) references glorri_vacancies (id) on update CASCADE on delete CASCADE,
  constraint duplicate_jobs_jobsearch_id_fkey foreign KEY (jobsearch_id) references js_vacancies (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

alter table public.glorri_companies enable row level security;
alter table public.glorri_vacancies enable row level security;
alter table public.js_companies enable row level security;
alter table public.js_vacancies enable row level security;
alter table public.duplicate_jobs enable row level security;

drop policy if exists "Enable read access for all users" on public.glorri_companies;
create policy "Enable read access for all users"
on public.glorri_companies
for select
to public
using (true);

drop policy if exists "Enable read access for all users" on public.glorri_vacancies;
create policy "Enable read access for all users"
on public.glorri_vacancies
for select
to public
using (true);

drop policy if exists "Enable read access for all users" on public.js_companies;
create policy "Enable read access for all users"
on public.js_companies
for select
to public
using (true);

drop policy if exists "Enable read access for all users" on public.js_vacancies;
create policy "Enable read access for all users"
on public.js_vacancies
for select
to public
using (true);

drop policy if exists "Enable read access for all users" on public.duplicate_jobs;
create policy "Enable read access for all users"
on public.duplicate_jobs
for select
to public
using (true);

-- Visits and clicks -----------------------------------------------------------

create table public.vacancy_visits (
  source text not null,
  vacancy_id bigint not null,
  visit_day date not null,
  visitor_hash text not null,
  slug text not null default '',
  created_at timestamp with time zone not null default now(),
  constraint vacancy_visits_pkey primary key (source, vacancy_id, visit_day, visitor_hash),
  constraint vacancy_visits_source_check check (source in ('jobsearch', 'glorri'))
) TABLESPACE pg_default;

create index if not exists vacancy_visits_visit_day_idx on public.vacancy_visits (visit_day desc);
create index if not exists vacancy_visits_vacancy_idx on public.vacancy_visits (source, vacancy_id, visit_day desc);

create or replace function public.increment_vacancy_visit(
  p_source text,
  p_vacancy_id bigint,
  p_slug text default '',
  p_visitor_ip text default ''
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_source text := lower(btrim(coalesce(p_source, '')));
  normalized_slug text := btrim(coalesce(p_slug, ''));
  normalized_ip text := btrim(coalesce(p_visitor_ip, ''));
  normalized_visit_day date := (now() at time zone 'utc')::date;
  hashed_visitor text;
begin
  if normalized_source not in ('jobsearch', 'glorri') then
    raise exception 'Invalid source: %', p_source;
  end if;

  if p_vacancy_id is null or p_vacancy_id <= 0 then
    raise exception 'Invalid vacancy id: %', p_vacancy_id;
  end if;

  if normalized_ip = '' then
    return;
  end if;

  hashed_visitor := md5(normalized_ip);

  insert into public.vacancy_visits (
    source,
    vacancy_id,
    visit_day,
    visitor_hash,
    slug,
    created_at
  )
  values (
    normalized_source,
    p_vacancy_id,
    normalized_visit_day,
    hashed_visitor,
    normalized_slug,
    now()
  )
  on conflict (source, vacancy_id, visit_day, visitor_hash)
  do nothing;
end;
$$;

revoke all on function public.increment_vacancy_visit(text, bigint, text, text) from public;
grant execute on function public.increment_vacancy_visit(text, bigint, text, text) to service_role;

alter table public.vacancy_visits enable row level security;

create table public.vacancy_clicks (
  id bigint generated by default as identity not null,
  source text not null,
  vacancy_id bigint not null,
  slug text not null default '',
  visitor_hash text not null default '',
  target_url text not null default '',
  clicked_at timestamp with time zone not null default now(),
  constraint vacancy_clicks_pkey primary key (id),
  constraint vacancy_clicks_source_check check (source in ('jobsearch', 'glorri'))
) TABLESPACE pg_default;

create index if not exists vacancy_clicks_clicked_at_idx on public.vacancy_clicks (clicked_at desc);
create index if not exists vacancy_clicks_vacancy_idx on public.vacancy_clicks (source, vacancy_id, clicked_at desc);

alter table public.vacancy_clicks enable row level security;

-- Auth profiles ---------------------------------------------------------------

create table public.profiles (
  id uuid not null,
  username text not null,
  first_name text not null,
  last_name text not null,
  created_at timestamp with time zone not null default now(),
  is_admin boolean not null default false,
  tech_stack jsonb not null default '[]'::jsonb,
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

-- Favorites ------------------------------------------------------------------

create table public.user_favorite_vacancies (
  user_id uuid not null,
  source text not null,
  vacancy_id bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint user_favorite_vacancies_pkey primary key (user_id, source, vacancy_id),
  constraint user_favorite_vacancies_user_fkey foreign key (user_id) references auth.users (id) on update cascade on delete cascade,
  constraint user_favorite_vacancies_source_check check (source in ('jobsearch', 'glorri'))
) tablespace pg_default;

create index if not exists user_favorite_vacancies_user_idx on public.user_favorite_vacancies (user_id);

alter table public.user_favorite_vacancies enable row level security;

drop policy if exists "Users can view own favorite vacancies" on public.user_favorite_vacancies;
create policy "Users can view own favorite vacancies"
  on public.user_favorite_vacancies for select
  using (auth.uid() = user_id);

drop policy if exists "Users can add own favorite vacancies" on public.user_favorite_vacancies;
create policy "Users can add own favorite vacancies"
  on public.user_favorite_vacancies for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can remove own favorite vacancies" on public.user_favorite_vacancies;
create policy "Users can remove own favorite vacancies"
  on public.user_favorite_vacancies for delete
  using (auth.uid() = user_id);

drop policy if exists "Service role full access on favorite vacancies" on public.user_favorite_vacancies;
create policy "Service role full access on favorite vacancies"
  on public.user_favorite_vacancies for all
  using (auth.role() = 'service_role');

create table public.user_favorite_companies (
  user_id uuid not null,
  source text not null,
  company_id bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint user_favorite_companies_pkey primary key (user_id, source, company_id),
  constraint user_favorite_companies_user_fkey foreign key (user_id) references auth.users (id) on update cascade on delete cascade,
  constraint user_favorite_companies_source_check check (source in ('jobsearch', 'glorri'))
) tablespace pg_default;

create index if not exists user_favorite_companies_user_idx on public.user_favorite_companies (user_id);

alter table public.user_favorite_companies enable row level security;

drop policy if exists "Users can view own favorite companies" on public.user_favorite_companies;
create policy "Users can view own favorite companies"
  on public.user_favorite_companies for select
  using (auth.uid() = user_id);

drop policy if exists "Users can add own favorite companies" on public.user_favorite_companies;
create policy "Users can add own favorite companies"
  on public.user_favorite_companies for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can remove own favorite companies" on public.user_favorite_companies;
create policy "Users can remove own favorite companies"
  on public.user_favorite_companies for delete
  using (auth.uid() = user_id);

drop policy if exists "Service role full access on favorite companies" on public.user_favorite_companies;
create policy "Service role full access on favorite companies"
  on public.user_favorite_companies for all
  using (auth.role() = 'service_role');

-- Notifications ---------------------------------------------------------------

create table public.notifications (
  id bigint generated always as identity not null,
  user_id uuid not null,
  type text not null,
  title text not null,
  body text,
  metadata jsonb not null default '{}'::jsonb,
  is_read boolean not null default false,
  created_at timestamp with time zone not null default now(),
  constraint notifications_pkey primary key (id),
  constraint notifications_user_fkey foreign key (user_id) references auth.users (id) on update cascade on delete cascade,
  constraint notifications_type_check check (type in ('vacancy_expired', 'new_company_vacancy'))
) tablespace pg_default;

create index if not exists notifications_user_unread_idx
  on public.notifications (user_id, is_read, created_at desc);

create index if not exists notifications_user_created_idx
  on public.notifications (user_id, created_at desc);

alter table public.notifications enable row level security;

drop policy if exists "Users can view own notifications" on public.notifications;
create policy "Users can view own notifications"
  on public.notifications for select
  using (auth.uid() = user_id);

drop policy if exists "Users can update own notifications" on public.notifications;
create policy "Users can update own notifications"
  on public.notifications for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Service role full access on notifications" on public.notifications;
create policy "Service role full access on notifications"
  on public.notifications for all
  using (auth.role() = 'service_role');

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'notifications'
    )
  then
    execute 'alter publication supabase_realtime add table public.notifications';
  end if;
end
$$;

-- Translations ----------------------------------------------------------------

create table public.vacancy_translations (
  source text not null,
  vacancy_id bigint not null,
  lang text not null,
  title text,
  text text,
  translated_at timestamp with time zone not null default now(),
  constraint vacancy_translations_pkey primary key (source, vacancy_id, lang),
  constraint vacancy_translations_source_check check (source in ('jobsearch', 'glorri')),
  constraint vacancy_translations_lang_check check (lang in ('en', 'az', 'ru'))
) tablespace pg_default;

create index if not exists vacancy_translations_lookup_idx
  on public.vacancy_translations (source, vacancy_id);

alter table public.vacancy_translations enable row level security;

drop policy if exists "Public can read vacancy translations" on public.vacancy_translations;
create policy "Public can read vacancy translations"
  on public.vacancy_translations for select
  using (true);

drop policy if exists "Service role can write vacancy translations" on public.vacancy_translations;
create policy "Service role can write vacancy translations"
  on public.vacancy_translations for all
  using (auth.role() = 'service_role');

create table public.company_translations (
  source text not null,
  company_id bigint not null,
  lang text not null,
  name text,
  description text,
  translated_at timestamp with time zone not null default now(),
  constraint company_translations_pkey primary key (source, company_id, lang),
  constraint company_translations_source_check check (source in ('jobsearch', 'glorri')),
  constraint company_translations_lang_check check (lang in ('en', 'az', 'ru'))
) tablespace pg_default;

create index if not exists company_translations_lookup_idx
  on public.company_translations (source, company_id);

alter table public.company_translations enable row level security;

drop policy if exists "Public can read company translations" on public.company_translations;
create policy "Public can read company translations"
  on public.company_translations for select
  using (true);

drop policy if exists "Service role can write company translations" on public.company_translations;
create policy "Service role can write company translations"
  on public.company_translations for all
  using (auth.role() = 'service_role');

-- Proxies and app settings ----------------------------------------------------

create table public.proxies (
  id bigint generated always as identity not null,
  url text not null,
  is_active boolean not null default true,
  last_used_at timestamp with time zone,
  fail_count integer not null default 0,
  created_at timestamp with time zone not null default now(),
  constraint proxies_pkey primary key (id),
  constraint proxies_url_unique unique (url)
) tablespace pg_default;

alter table public.proxies enable row level security;

drop policy if exists "Service role full access on proxies" on public.proxies;
create policy "Service role full access on proxies"
  on public.proxies for all
  using (auth.role() = 'service_role');

create table public.app_settings (
  key text not null,
  value text not null,
  updated_at timestamp with time zone not null default now(),
  constraint app_settings_pkey primary key (key)
) tablespace pg_default;

alter table public.app_settings enable row level security;

drop policy if exists "Service role full access on app_settings" on public.app_settings;
create policy "Service role full access on app_settings"
  on public.app_settings for all
  using (auth.role() = 'service_role');

insert into public.app_settings (key, value)
values ('translation_enabled', 'true')
on conflict (key) do nothing;

-- Telegram bot ----------------------------------------------------------------

create table public.telegram_user_settings (
  chat_id bigint primary key,
  username text,
  first_name text,
  language_code text not null default 'az',
  selected_technologies jsonb not null default '[]'::jsonb,
  onboarding_step text not null default 'language',
  active boolean not null default true,
  last_digest_for date,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_telegram_user_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists telegram_user_settings_set_updated_at on public.telegram_user_settings;
create trigger telegram_user_settings_set_updated_at
before update on public.telegram_user_settings
for each row
execute function public.set_telegram_user_settings_updated_at();
