create table if not exists public.vacancy_clicks (
  id bigint generated by default as identity not null,
  source text not null,
  vacancy_id bigint not null,
  slug text not null default '',
  visitor_hash text not null default '',
  target_url text not null default '',
  clicked_at timestamp with time zone not null default now(),
  constraint vacancy_clicks_pkey primary key (id),
  constraint vacancy_clicks_source_check check (source in ('jobsearch', 'glorri'))
) TABLESPACE pg_default;

create index if not exists vacancy_clicks_clicked_at_idx on public.vacancy_clicks (clicked_at desc);
create index if not exists vacancy_clicks_vacancy_idx on public.vacancy_clicks (source, vacancy_id, clicked_at desc);

alter table public.vacancy_clicks enable row level security;
